; PlatformIO Project Configuration File

[env:sipeed-maix-go]
platform = kendryte210
board = sipeed-maix-go
framework = arduino

[env:yehuo]
platform = kendryte210
board = yehuo_k210
framework = arduino
lib_extra_dirs = 
    C:\Users\Lenovo\.platformio\packages\framework-maixduino\libraries
build_flags = 
    -I${PROJECT_DIR}
    -I${PROJECT_DIR}/include
lib_deps =
    lvgl/lvgl@^9.5.0

