; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:yehuo]
platform = kendryte210
board = yehuo_k210
framework = arduino
build_type = debug
monitor_speed = 115200
build_flags = 
	-D APP_LOG_LEVEL=3
	-D APP_SD_FS_LOG_ENABLE=1
build_src_flags = 
	-Wall
	-Wextra
	-Werror
build_src_filter = 
	+<*>
	-<driver/sd_card.cpp>
	-<driver/sd_hw_v2.cpp>
lib_deps = 
	lvgl/lvgl@^9.5.0
	adafruit/SdFat - Adafruit Fork@^2.3.103
